# Generated by Django 5.0.7 on 2024-07-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='camdb',
            name='camdb_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
